### ISSUE TITLE
Code licensing.

### ISSUE THREAD

**Issue by Fenix2412** [wyldbrian/Python#2]
Hello I recently started a project of my own (https://gitlab.com/Fenix2412/IRCBot) based on your karmabot and I would like to know what is the licensing on that code so I can adjust my license accordingly.

**Comment by wyldbrian** [comment]
Damian,


Sorry for the delayed response, I just added a license to the Python repo.


https://github.com/wyldbrian/Python/blob/master/LICENSE.md


Also, if you're building an IRC bot, check out the Turing directory under my python repo, it's much more exciting and active.


Thank you,


-Brian

________________________________

**Comment by wyldbrian** [comment]
MIT license applied
